### ISSUE TITLE
Technician todo site

### ISSUE THREAD

**Issue by DrunkenToast** [tm-pe2/ad-website#11]
- [ ] Pull required information from database

- [ ] Show the jobs left to do by technician
    - [ ] Filter on where, when, how urgent
    - [x] Show required information
    - [ ] Required tools (if it's a different model that requires different tools that you don't have etc etc)

- [ ] Show completed jobs within a certain time frame

- [ ] Push notifications via mail
